version: "3.9"

services:
  app:
    build: .
    networks:
      - main
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
      - dev-static-data:/vol/web
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py create_superuser &&
             python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASS=devpass
      - DEBUG=1
    depends_on:
      - db
      - rabbitmq

  db:
    image: postgres:13-alpine
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=devpass
    networks:
      - main

  rabbitmq:
    container_name: rabbitmq
    hostname: rabbitmq
    image: rabbitmq:latest
    networks:
      - main
    ports:
      - "5672:5672"

  celery:
    build: .
    command: sh -c "celery -A project worker -l info"
    volumes:
      - ./app:/app
    networks:
      - main
    depends_on:
      - app
      - db
      - rabbitmq
    environment:
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASS=devpass

networks:
  main:


volumes:
  dev-db-data:
  dev-static-data:
